<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>try, catch, throw e finally</title>
</head>
<body>
    <script>/*
        //NetFlix
        var video = Array()

        video[1] = Array()
        video[1]['nome'] = 'Fullmetal Alchemist'
        video[1]['categoria'] = 'Anime'

        function getVideo(){
            //lógica
            //http        
            try {
            // coloque o possivel erro no try
                console.log(video[0]['nome'])
            } 
        
            catch(e){
                tratarErro(e)
                console.log('Mesmo com o erro acontecendo, podemos trata-lo de uma forma criativa')
            //no caso do throw precisa instanciar, e ele não é um bloco de código como (try, catch e finally)
                throw new Error('Houve um erro mas não se preocupe, estamos trabalhando nisso')
            }

            finally {
            // e o finally recebe os dois
                console.log('Sempre passa por aqui vindo do (try ou do catch)')
            }

            console.log(video[1])
            console.log('A aplicação não morreu')
            }

                function tratarErro(e){
                console.log(e)
                }

        getVideo(video)*/
    </script>   
</body>
</html>